source ./setenv.sh consumer

export QUEUE_TYPE=$1

echo ${ABSPATH2CLASSES}
cd ${ABSPATH2CLASSES}
#clear
#pwd  
java -cp ${CLASSPATH} \
     ${JAVAPACKAGEROLEPATH}.${CONSUMER_CLASS_PREFIX} ${BROKER_HOST} ${BROKER_PORT} ${QUEUE_TYPE}

echo ${ABSPATH2SRC}/${JAVASCRIPTSPATH}
cd ${ABSPATH2SRC}/${JAVASCRIPTSPATH}
#pwd